version: "3.8"

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:latest
    container_name: rocketchat
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
      - ROOT_URL=http://localhost:3000
      - PORT=3000
    ports:
      - 3036:3000

  mongo:
    image: mongo:6.0
    container_name: rocketchat_mongo
    restart: always
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    volumes:
      /var/docker-var/rocketchat/rocketchat_mongo_data:/data/db
      /var/docker-var/rocketchatrocketchat_mongo_config:/data/configdb

  mongo-init-replica:
    image: mongo:6.0
    depends_on:
      - mongo
    entrypoint: >
      bash -c "for i in `seq 1 30`; do
        mongo mongo/rocketchat --eval 'rs.initiate()' && break || sleep 1;
      done"
    restart: "no"

