version: "3"

services:
  docmost:
    image: docmost/docmost:latest
    depends_on:
      - db
      - redis
    environment:
      APP_URL: "http://localhost:3000"
      APP_SECRET: "0xrK5j3ch9sg0xrK5j3ch9sg0xrK5j3ch9sg"
      DATABASE_URL: "postgresql://docmost:B8P7MVM6OYCk@db:5432/docmost?schema=public"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "3001:3000"
    restart: always
    volumes:
      - /var/docker-var/docmost/application-data:/app/data/storage

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: B8P7MVM6OYCk
    restart: always
    volumes:
      - /var/docker-var/docmost/db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    volumes:
      - /var/docker-var/docmost/redis_data:/data

