version: '3.8'

services:
  db:
    image: postgres:15
    container_name: myfin-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-myfin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-myfin}
    volumes:
      - /var/docker-var/myfin/postgres-data:/var/lib/postgresql/data


  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myfin-api
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-myfin}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-myfin}
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
    ports:
      - "${PORT:-3096}:3000"

  pruner:
    image: ghcr.io/afaneca/myfin-api-pruner:latest
    container_name: myfin-pruner
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-myfin}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-myfin}
    entrypoint: ["node", "dist/pruner.js"]
