
version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - 8088:8080
      - 50000:50000
    volumes:
      /var/docker-var/jenkins/home:/var/jenkins_home
      /var/run/docker.sock:/var/run/docker.sock
    user: root

