version: '3'
services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    ports:
      - 2222:2222
      - 8888:8888
      - 33306:33306
    volumes:
      - /var/docker-var/warpgate:/data
      - /var/lib/warpgate:/var/lib/warpgate
    stdin_open: true
    tty: true

