version: "3"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    restart: always
    ports:
      - "3004:3001"
    volumes:
      - /var/docker-var/uptimekuma/data:/app/data