version: '3.8'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Dhaka
    volumes:
      - /var/docker-var/syncthing/config:/config
      - /var/docker-var/syncthing/sync:/sync
    ports:
      - 8384:8384     # Web UI
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp  # Local discovery
    restart: unless-stopped
