services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /var/docker-var/nginx-proxy-manager/data:/data
      - /var/docker-var/nginx-proxy-manager/letsencrypt:/etc/letsencrypt